snips_labels = ['playlist', 'music_item', 'geographic_poi', 'facility', 'movie_name', 'location_name',
                'restaurant_name', 'track', 'restaurant_type', 'object_part_of_series_type', 'country',
                'service', 'poi', 'party_size_description', 'served_dish', 'genre', 'current_location',
                'object_select', 'album', 'object_name', 'state', 'sort', 'object_location_type', 'movie_type',
                'spatial_relation', 'artist', 'cuisine', 'entity_name', 'object_type', 'playlist_owner',
                'timeRange', 'city', 'rating_value', 'best_rating', 'rating_unit', 'year', 'party_size_number',
                'condition_description', 'condition_temperature', 'O']

snips_domain2desp = {
    "AddToPlaylist": "add to playlist", "BookRestaurant": "reserve restaurant", "GetWeather": "get weather",
    "PlayMusic": "play music", "RateBook": "rate book", "SearchCreativeWork": "search creative work",
    "SearchScreeningEvent": "search screening event"
}

snips_index_dict = {'AddToPlaylist': [1, 29, 27, 0, 25, 39],
                    'BookRestaurant': [31, 3, 30, 6, 10, 26, 8, 14, 36, 12, 21, 24, 20, 13, 39],
                    'GetWeather': [31, 20, 30, 16, 10, 24, 2, 38, 37, 39],
                    'PlayMusic': [15, 1, 11, 35, 0, 18, 21, 7, 25, 39],
                    'RateBook': [9, 17, 32, 19, 28, 34, 33, 39],
                    'SearchCreativeWork': [19, 28, 39],
                    'SearchScreeningEvent': [30, 23, 22, 28, 5, 24, 4, 39]}

snips_valid_labels = ['B-playlist', 'I-playlist', 'B-music_item', 'I-music_item', 'B-geographic_poi',
                      'I-geographic_poi', 'B-facility', 'I-facility', 'B-movie_name', 'I-movie_name',
                      'B-location_name', 'I-location_name', 'B-restaurant_name', 'I-restaurant_name', 'B-track',
                      'I-track', 'B-restaurant_type', 'I-restaurant_type', 'B-object_part_of_series_type',
                      'I-object_part_of_series_type', 'B-country', 'I-country', 'B-service', 'I-service', 'B-poi',
                      'I-poi', 'B-party_size_description', 'I-party_size_description', 'B-served_dish',
                      'I-served_dish', 'B-genre', 'I-genre', 'B-current_location', 'I-current_location',
                      'B-object_select', 'I-object_select', 'B-album', 'I-album', 'B-object_name', 'I-object_name',
                      'B-state', 'I-state', 'B-sort', 'I-sort', 'B-object_location_type', 'I-object_location_type',
                      'B-movie_type', 'I-movie_type', 'B-spatial_relation', 'I-spatial_relation', 'B-artist',
                      'I-artist', 'B-cuisine', 'I-cuisine', 'B-entity_name', 'I-entity_name', 'B-object_type',
                      'I-object_type', 'B-playlist_owner', 'I-playlist_owner', 'B-timeRange', 'I-timeRange', 'B-city',
                      'I-city', 'B-rating_value', 'B-best_rating', 'B-rating_unit', 'B-year', 'B-party_size_number',
                      'B-condition_description', 'B-condition_temperature', 'O']

atis_labels = ['arrive_date.month_name', 'depart_date.date_relative', 'stoploc.airport_name', 'fromloc.city_name',
               'class_type', 'flight_stop', 'day_name', 'depart_date.today_relative', 'fromloc.state_code',
               'stoploc.state_code',
               'fromloc.airport_code', 'flight_mod', 'arrive_time.start_time', 'toloc.city_name', 'arrive_time.time',
               'arrive_date.today_relative',
               'depart_time.start_time', 'depart_time.end_time', 'arrive_date.date_relative', 'return_date.day_name',
               'time_relative', 'state_code',
               'stoploc.airport_code', 'booking_class', 'days_code', 'flight', 'depart_date.day_name',
               'return_date.today_relative', 'meal',
               'return_date.day_number', 'arrive_date.day_number', 'or', 'transport_type', 'toloc.country_name',
               'depart_time.period_of_day',
               'arrive_time.end_time', 'meal_code', 'airline_code', 'round_trip', 'day_number',
               'depart_date.month_name', 'return_time.period_of_day',
               'time', 'state_name', 'depart_time.period_mod', 'fromloc.airport_name', 'flight_days',
               'toloc.state_name', 'depart_time.time', 'toloc.airport_name',
               'airport_code', 'connect', 'economy', 'stoploc.city_name', 'period_of_day', 'toloc.state_code', 'mod',
               'toloc.airport_code', 'arrive_time.period_of_day',
               'compartment', 'cost_relative', 'arrive_time.time_relative', 'month_name', 'depart_date.year',
               'arrive_date.day_name', 'city_name', 'fare_basis_code',
               'meal_description', 'aircraft_code', 'return_time.period_mod', 'fromloc.state_name', 'airport_name',
               'flight_number', 'restriction_code',
               'depart_date.day_number', 'arrive_time.period_mod', 'fare_amount', 'airline_name', 'flight_time',
               'today_relative', 'depart_time.time_relative',
               'return_date.month_name', 'return_date.date_relative', 'O']

atis_valid_labels = ['I-flight_time', 'B-restriction_code', 'I-fare_basis_code', 'I-transport_type',
                     'B-return_time.period_mod',
                     'B-toloc.country_name', 'B-flight', 'I-toloc.state_name', 'B-fromloc.state_code',
                     'B-arrive_time.start_time', 'I-airline_name',
                     'B-arrive_time.period_mod', 'I-return_date.day_number', 'I-meal_description',
                     'B-depart_time.time_relative', 'B-cost_relative',
                     'B-depart_date.month_name', 'B-aircraft_code', 'B-toloc.city_name', 'B-depart_date.year',
                     'B-connect', 'I-return_date.date_relative',
                     'B-airport_name', 'B-meal_description', 'B-depart_date.day_name', 'B-flight_stop',
                     'I-airport_name', 'B-class_type', 'B-arrive_time.end_time',
                     'B-days_code', 'I-round_trip', 'B-state_code', 'B-return_time.period_of_day', 'B-flight_mod',
                     'B-depart_time.period_mod', 'B-arrive_time.time',
                     'I-stoploc.city_name', 'B-return_date.date_relative', 'B-period_of_day',
                     'B-return_date.month_name', 'B-toloc.state_name', 'B-day_name',
                     'B-stoploc.city_name', 'I-today_relative', 'B-toloc.state_code', 'B-meal_code',
                     'B-stoploc.airport_code', 'B-arrive_time.period_of_day',
                     'B-arrive_date.day_number', 'B-toloc.airport_name', 'B-stoploc.state_code', 'I-city_name',
                     'B-state_name', 'B-depart_date.day_number',
                     'B-return_date.today_relative', 'I-return_date.today_relative', 'I-flight_number',
                     'I-fromloc.airport_name', 'I-depart_time.time',
                     'I-depart_time.period_of_day', 'B-today_relative', 'B-arrive_date.day_name',
                     'I-arrive_time.end_time', 'I-depart_time.time_relative',
                     'B-fromloc.airport_code', 'I-toloc.city_name', 'B-depart_time.end_time', 'B-flight_number',
                     'I-fromloc.city_name', 'B-transport_type',
                     'B-round_trip', 'I-flight_stop', 'B-depart_time.period_of_day', 'I-arrive_time.period_of_day',
                     'B-compartment', 'B-flight_time',
                     'B-return_date.day_number', 'B-month_name', 'B-airport_code', 'B-depart_time.start_time',
                     'I-restriction_code', 'B-mod', 'I-arrive_time.start_time',
                     'B-time_relative', 'I-depart_date.day_number', 'B-economy', 'I-state_name',
                     'B-arrive_date.date_relative', 'B-fromloc.city_name',
                     'B-depart_date.today_relative', 'B-fare_amount', 'I-fromloc.state_name',
                     'B-arrive_time.time_relative', 'I-arrive_time.time',
                     'I-toloc.airport_name', 'I-economy', 'I-arrive_time.time_relative', 'I-time',
                     'I-depart_date.today_relative', 'B-depart_date.date_relative',
                     'I-fare_amount', 'B-stoploc.airport_name', 'B-booking_class', 'I-meal_code',
                     'B-fromloc.state_name', 'B-meal', 'B-arrive_date.month_name',
                     'I-depart_time.start_time', 'B-airline_code', 'B-arrive_date.today_relative', 'I-flight_mod',
                     'B-or', 'B-toloc.airport_code', 'I-cost_relative',
                     'I-class_type', 'B-time', 'I-arrive_date.day_number', 'B-fromloc.airport_name', 'B-day_number',
                     'B-airline_name', 'I-depart_time.end_time',
                     'B-return_date.day_name', 'B-city_name', 'B-depart_time.time', 'B-fare_basis_code',
                     'B-flight_days', 'O']

atis_label_dict = {
    'atis_flight': ['flight_days', 'return_date.day_number', 'arrive_date.day_number', 'toloc.state_name',
                    'depart_time.time',
                    'arrive_date.month_name', 'fare_basis_code', 'toloc.airport_name', 'depart_date.date_relative',
                    'meal_description',
                    'stoploc.airport_name', 'fromloc.city_name', 'or', 'airport_code', 'class_type', 'flight_stop',
                    'day_name', 'connect',
                    'aircraft_code', 'economy', 'stoploc.city_name', 'return_date.date_relative', 'fromloc.state_name',
                    'period_of_day',
                    'return_time.period_mod', 'airport_name', 'toloc.country_name', 'depart_date.today_relative',
                    'toloc.state_code',
                    'mod', 'toloc.airport_code', 'depart_time.period_of_day', 'fromloc.state_code', 'flight_number',
                    'stoploc.state_code',
                    'arrive_time.end_time', 'fromloc.airport_code', 'flight_mod', 'arrive_time.start_time',
                    'toloc.city_name', 'arrive_time.period_of_day',
                    'arrive_time.time', 'airline_code', 'arrive_date.today_relative', 'depart_date.day_number',
                    'depart_time.start_time',
                    'depart_time.end_time', 'return_date.day_name', 'arrive_date.date_relative',
                    'arrive_time.period_mod', 'fare_amount',
                    'stoploc.airport_code', 'airline_name', 'compartment', 'cost_relative', 'arrive_time.time_relative',
                    'flight_time',
                    'round_trip', 'depart_time.time_relative', 'depart_date.month_name', 'depart_date.year',
                    'return_time.period_of_day',
                    'flight', 'return_date.month_name', 'depart_date.day_name', 'arrive_date.day_name',
                    'depart_time.period_mod',
                    'return_date.today_relative', 'city_name', 'fromloc.airport_name', 'meal', 'O'],

    'atis_airfare': ['flight_days', 'return_date.day_number', 'arrive_date.day_number', 'toloc.state_name',
                     'depart_time.time',
                     'arrive_date.month_name', 'toloc.airport_name', 'depart_date.date_relative', 'fromloc.city_name',
                     'or', 'class_type',
                     'flight_stop', 'connect', 'aircraft_code', 'economy', 'stoploc.city_name', 'fromloc.state_name',
                     'toloc.state_code',
                     'depart_date.today_relative', 'toloc.airport_code', 'depart_time.period_of_day',
                     'fromloc.state_code', 'flight_number',
                     'fromloc.airport_code', 'flight_mod', 'toloc.city_name', 'airline_code', 'arrive_time.time',
                     'arrive_date.date_relative',
                     'depart_date.day_number', 'fare_amount', 'airline_name', 'cost_relative',
                     'arrive_time.time_relative', 'flight_time',
                     'round_trip', 'depart_time.time_relative', 'depart_date.month_name', 'depart_date.year',
                     'return_date.month_name',
                     'depart_date.day_name', 'arrive_date.day_name', 'depart_time.period_mod', 'fromloc.airport_name',
                     'meal', 'O'],

    'atis_airline': ['flight_days', 'arrive_date.day_number', 'toloc.state_name', 'depart_time.time',
                     'arrive_date.month_name', 'toloc.airport_name',
                     'depart_date.date_relative', 'fromloc.city_name', 'class_type', 'flight_stop', 'connect',
                     'aircraft_code', 'stoploc.city_name',
                     'airport_name', 'depart_date.today_relative', 'toloc.state_code', 'mod',
                     'depart_time.period_of_day', 'fromloc.state_code',
                     'flight_number', 'fromloc.airport_code', 'toloc.city_name', 'arrive_time.period_of_day',
                     'airline_code', 'arrive_time.time',
                     'depart_time.start_time', 'depart_date.day_number', 'depart_time.end_time', 'airline_name',
                     'cost_relative', 'depart_time.time_relative',
                     'round_trip', 'depart_date.month_name', 'depart_date.day_name', 'city_name',
                     'fromloc.airport_name', 'O'],

    'atis_ground_service': ['toloc.airport_name', 'depart_date.date_relative', 'airport_code', 'fromloc.city_name',
                            'or', 'day_name', 'period_of_day',
                            'transport_type', 'airport_name', 'toloc.city_name', 'depart_date.day_number',
                            'time_relative', 'state_code', 'flight_time',
                            'today_relative', 'day_number', 'month_name', 'time', 'depart_date.month_name',
                            'state_name', 'depart_date.day_name',
                            'city_name', 'fromloc.airport_name', 'O'],
    'atis_abbreviation': ['airline_name', 'booking_class', 'restriction_code', 'days_code', 'fare_basis_code',
                          'aircraft_code', 'meal_code',
                          'toloc.city_name', 'airline_code', 'airport_code', 'fromloc.city_name', 'mod', 'class_type',
                          'meal', 'O'],

    'others': ['flight_days', 'arrive_date.day_number', 'toloc.state_name', 'depart_time.time',
               'arrive_date.month_name', 'fare_basis_code',
               'toloc.airport_name', 'depart_date.date_relative', 'airport_code', 'meal_description',
               'fromloc.city_name', 'arrive_date.day_name',
               'or', 'class_type', 'flight_stop', 'aircraft_code', 'economy', 'stoploc.city_name', 'fromloc.state_name',
               'transport_type',
               'airport_name', 'depart_date.today_relative', 'toloc.state_code', 'toloc.airport_code', 'mod',
               'depart_time.period_of_day',
               'flight_number', 'fromloc.airport_code', 'restriction_code', 'flight_mod', 'toloc.city_name',
               'airline_code', 'arrive_time.time',
               'depart_date.day_number', 'return_date.day_name', 'state_code', 'fare_amount', 'airline_name',
               'cost_relative', 'arrive_time.time_relative',
               'flight_time', 'round_trip', 'depart_time.time_relative', 'depart_date.month_name', 'state_name',
               'depart_date.day_name',
               'return_date.date_relative', 'city_name', 'fromloc.airport_name', 'meal', 'O']}

sgd_labels = ['time', 'movie_title', 'price_per_night', 'check_out_date', 'destination', 'balance', 'fare',
              'to_station', 'outbound_departure_time',
              'place_name', 'city', 'alarm_name', 'stylist_name', 'pickup_city', 'date_of_journey', 'amount',
              'destination_airport', 'return_date',
              'venue_address', 'street_address', 'stay_length', 'start_date', 'starring', 'actors', 'rating',
              'attraction_name', 'event_location', 'rent',
              'doctor_name', 'precipitation', 'therapist_name', 'average_rating', 'cuisine', 'leaving_time',
              'to_location', 'price_per_day', 'area',
              'approximate_ride_duration', 'date', 'origin_city', 'to_city', 'phone_number', 'total', 'show_time',
              'journey_start_time',
              'percent_rating', 'hotel_name', 'event_date', 'show_date', 'origin_airport', 'transfer_time',
              'appointment_date', 'origin_airport_name',
              'directed_by', 'available_end_time', 'from_location', 'wait_time', 'dentist_name', 'from_city', 'title',
              'end_date', 'departure_time',
              'departure_date', 'wind', 'price_per_ticket', 'destination_airport_name', 'genre', 'track',
              'aggregate_rating', 'check_in_date', 'pickup_date',
              'recipient_account_name', 'transfer_amount', 'property_name', 'new_alarm_time', 'director', 'cast',
              'subcategory', 'destination_city', 'to',
              'visit_date', 'outbound_arrival_time', 'origin_station_name', 'address_of_location', 'artist',
              'event_time', 'pickup_time', 'new_alarm_name',
              'temperature', 'origin', 'receiver', 'venue', 'inbound_departure_time', 'from_station', 'album',
              'event_name', 'ride_fare', 'recipient_name',
              'inbound_arrival_time', 'leaving_date', 'account_balance', 'from', 'song_name', 'address', 'theater_name',
              'price', 'restaurant_name',
              'contact_name', 'available_start_time', 'car_name', 'location', 'appointment_time', 'number_of_days',
              'category', 'pickup_location',
              'where_to', 'total_price', 'dropoff_date', 'humidity', 'destination_station_name', 'alarm_time',
              'city_of_event', 'movie_name', 'O']

sgd_valid_labels = ['I-venue_address', 'B-start_date', 'I-destination_city', 'B-return_date', 'B-price_per_day',
                    'I-destination_station_name', 'B-total',
                    'B-venue_address', 'I-inbound_arrival_time', 'I-check_in_date', 'I-outbound_arrival_time',
                    'B-leaving_time', 'B-departure_time', 'I-venue',
                    'B-journey_start_time', 'I-date_of_journey', 'I-alarm_name', 'B-track', 'B-available_end_time',
                    'B-alarm_time', 'B-event_date', 'B-pickup_date',
                    'B-destination_city', 'B-place_name', 'B-dropoff_date', 'B-from_city', 'I-new_alarm_name',
                    'I-origin_airport', 'I-event_location',
                    'I-inbound_departure_time', 'B-check_out_date', 'B-address', 'I-leaving_date', 'I-from_location',
                    'B-pickup_time', 'B-movie_name',
                    'B-rent', 'B-event_location', 'B-rating', 'B-destination_station_name', 'B-fare', 'I-doctor_name',
                    'I-category', 'I-destination_airport',
                    'B-ride_fare', 'I-event_time', 'I-show_time', 'B-show_date', 'B-contact_name', 'I-artist', 'I-date',
                    'B-percent_rating', 'B-destination_airport_name',
                    'I-street_address', 'B-outbound_arrival_time', 'B-destination_airport', 'I-subcategory',
                    'B-category', 'B-balance', 'B-movie_title',
                    'B-receiver', 'B-outbound_departure_time', 'I-property_name', 'B-leaving_date',
                    'I-appointment_date', 'B-transfer_amount', 'B-average_rating',
                    'B-time', 'B-director', 'I-available_end_time', 'B-genre', 'B-directed_by', 'I-alarm_time',
                    'I-actors', 'B-to_station', 'I-amount',
                    'I-phone_number', 'I-pickup_time', 'I-origin_city', 'B-pickup_city', 'B-transfer_time',
                    'I-transfer_amount', 'I-therapist_name',
                    'B-location', 'B-subcategory', 'I-restaurant_name', 'I-theater_name', 'I-to', 'B-event_name',
                    'I-location', 'B-from', 'B-amount',
                    'I-available_start_time', 'I-check_out_date', 'I-from', 'B-stay_length', 'I-hotel_name',
                    'I-starring', 'B-date_of_journey',
                    'B-venue', 'I-genre', 'B-departure_date', 'I-to_city', 'B-origin', 'B-restaurant_name',
                    'B-stylist_name', 'B-pickup_location',
                    'I-event_name', 'I-origin_airport_name', 'B-address_of_location', 'I-event_date',
                    'B-approximate_ride_duration', 'B-hotel_name', 'B-song_name',
                    'I-director', 'I-area', 'B-wind', 'I-show_date', 'I-movie_name', 'I-to_station', 'I-start_date',
                    'B-new_alarm_time', 'I-outbound_departure_time',
                    'I-address', 'I-from_station', 'I-new_alarm_time', 'B-price_per_night', 'I-return_date',
                    'B-appointment_time', 'B-check_in_date', 'I-dentist_name',
                    'I-address_of_location', 'B-recipient_account_name', 'I-pickup_date', 'B-cast', 'B-number_of_days',
                    'B-account_balance', 'I-city', 'I-album',
                    'I-to_location', 'B-new_alarm_name', 'B-destination', 'B-origin_station_name', 'B-actors',
                    'B-aggregate_rating', 'B-alarm_name', 'B-temperature',
                    'B-street_address', 'I-car_name', 'I-city_of_event', 'I-cast', 'B-album',
                    'I-destination_airport_name', 'B-price', 'I-journey_start_time',
                    'B-end_date', 'B-theater_name', 'B-attraction_name', 'I-attraction_name', 'I-from_city',
                    'I-place_name', 'B-appointment_date',
                    'B-inbound_arrival_time', 'I-movie_title', 'B-show_time', 'B-wait_time', 'I-song_name',
                    'I-departure_time', 'I-visit_date', 'B-total_price',
                    'B-title', 'B-starring', 'I-pickup_city', 'B-visit_date', 'I-track', 'B-price_per_ticket',
                    'B-event_time', 'I-destination', 'I-departure_date',
                    'I-leaving_time', 'B-recipient_name', 'I-cuisine', 'B-to_location', 'B-cuisine', 'B-phone_number',
                    'I-end_date', 'B-available_start_time', 'B-where_to',
                    'B-origin_airport', 'B-date', 'B-from_location', 'B-humidity', 'I-pickup_location', 'I-origin',
                    'B-area', 'I-stylist_name', 'B-property_name',
                    'B-origin_city', 'B-dentist_name', 'B-precipitation', 'I-title', 'B-city_of_event',
                    'I-recipient_name', 'B-inbound_departure_time',
                    'B-origin_airport_name', 'B-doctor_name', 'B-car_name', 'I-dropoff_date', 'I-time', 'I-directed_by',
                    'B-to', 'B-to_city', 'I-origin_station_name',
                    'I-appointment_time', 'B-artist', 'B-from_station', 'B-city', 'I-where_to', 'B-therapist_name', 'O']

sgd_label_dict = {
    'Restaurants': ['ride_fare', 'time', 'rating', 'event_location', 'movie_title', 'genre', 'average_rating',
                    'cuisine', 'account_balance',
                    'approximate_ride_duration', 'date', 'phone_number', 'destination', 'show_time', 'address',
                    'theater_name', 'price',
                    'restaurant_name', 'percent_rating', 'cast', 'show_date', 'city', 'location', 'stylist_name',
                    'directed_by', 'wait_time',
                    'category', 'street_address', 'movie_name', 'O'],

    'Events': ['ride_fare', 'start_date', 'starring', 'time', 'rating', 'attraction_name', 'event_location',
               'movie_title', 'precipitation',
               'leaving_date', 'genre', 'average_rating', 'cuisine', 'account_balance', 'price_per_day',
               'price_per_night', 'aggregate_rating',
               'approximate_ride_duration', 'date', 'phone_number', 'destination', 'pickup_date', 'song_name',
               'balance', 'address', 'wind',
               'hotel_name', 'percent_rating', 'event_date', 'director', 'cast', 'subcategory', 'place_name', 'city',
               'event_name', 'available_start_time',
               'address_of_location', 'directed_by', 'available_end_time', 'artist', 'price_per_ticket', 'pickup_time',
               'wait_time', 'category',
               'temperature', 'title', 'pickup_location', 'end_date', 'departure_date', 'humidity', 'venue',
               'city_of_event', 'return_date',
               'venue_address', 'street_address', 'movie_name', 'album', 'O'],
    'Music': ['starring', 'actors', 'movie_title', 'genre', 'cuisine', 'track', 'aggregate_rating', 'song_name',
              'price', 'percent_rating',
              'director', 'cast', 'alarm_name', 'directed_by', 'artist', 'title', 'alarm_time', 'movie_name', 'album',
              'O'],

    'Movies': ['album', 'ride_fare', 'starring', 'time', 'actors', 'attraction_name', 'event_location', 'movie_title',
               'genre', 'cuisine',
               'account_balance', 'track', 'aggregate_rating', 'approximate_ride_duration', 'date', 'phone_number',
               'destination', 'balance',
               'song_name', 'show_time', 'theater_name', 'price', 'percent_rating', 'restaurant_name', 'director',
               'cast', 'subcategory', 'show_date',
               'city', 'location', 'alarm_name', 'address_of_location', 'directed_by', 'artist', 'wait_time',
               'category', 'title', 'venue', 'alarm_time',
               'venue_address', 'street_address', 'movie_name', 'event_name', 'O'],

    'Flights': ['start_date', 'time', 'rating', 'attraction_name', 'event_location', 'inbound_arrival_time',
                'leaving_date', 'genre', 'average_rating',
                'leaving_time', 'to_location', 'account_balance', 'price_per_night', 'check_out_date', 'from', 'date',
                'origin_city', 'phone_number',
                'destination', 'total', 'check_in_date', 'pickup_date', 'fare', 'song_name', 'address',
                'destination_airport_name', 'journey_start_time',
                'to_station', 'price', 'outbound_departure_time', 'hotel_name', 'subcategory', 'place_name',
                'destination_city', 'origin_airport',
                'event_name', 'city', 'to', 'origin_airport_name', 'outbound_arrival_time', 'origin_station_name',
                'location', 'address_of_location',
                'from_location', 'artist', 'category', 'departure_time', 'pickup_location', 'where_to', 'origin',
                'dropoff_date', 'departure_date',
                'date_of_journey', 'destination_station_name', 'inbound_departure_time', 'venue', 'destination_airport',
                'from_station', 'return_date',
                'city_of_event', 'venue_address', 'street_address', 'price_per_ticket', 'album', 'O'],

    'RideSharing': ['album', 'ride_fare', 'destination', 'song_name', 'genre', 'artist', 'cuisine', 'track',
                    'wait_time', 'approximate_ride_duration', 'O'],

    'RentalCars': ['start_date', 'rating', 'attraction_name', 'rent', 'leaving_date', 'average_rating', 'price_per_day',
                   'price_per_night', 'check_out_date',
                   'phone_number', 'destination', 'check_in_date', 'pickup_date', 'address', 'property_name',
                   'hotel_name', 'city', 'visit_date', 'car_name',
                   'location', 'pickup_city', 'pickup_time', 'end_date', 'pickup_location', 'total_price',
                   'dropoff_date', 'street_address', 'movie_name', 'O'],

    'Buses': ['start_date', 'time', 'rating', 'attraction_name', 'movie_title', 'leaving_date', 'average_rating',
              'leaving_time', 'to_location',
              'price_per_night', 'date', 'origin_city', 'to_city', 'phone_number', 'destination', 'check_in_date',
              'pickup_date', 'fare', 'address',
              'destination_airport_name', 'to_station', 'price', 'outbound_departure_time', 'hotel_name',
              'percent_rating', 'place_name', 'destination_city',
              'city', 'origin_airport', 'origin_airport_name', 'outbound_arrival_time', 'origin_station_name',
              'alarm_name', 'from_location', 'pickup_city',
              'category', 'from_city', 'departure_time', 'origin', 'departure_date', 'destination_station_name',
              'venue', 'inbound_departure_time',
              'alarm_time', 'destination_airport', 'from_station', 'return_date', 'venue_address', 'street_address',
              'price_per_ticket', 'event_name', 'O'],

    'Hotels': ['stay_length', 'start_date', 'rating', 'attraction_name', 'precipitation', 'leaving_date', 'genre',
               'average_rating', 'track', 'price_per_day',
               'price_per_night', 'check_out_date', 'date', 'phone_number', 'destination', 'check_in_date',
               'pickup_date', 'song_name', 'address', 'price',
               'hotel_name', 'place_name', 'location', 'artist', 'pickup_time', 'number_of_days', 'temperature',
               'end_date', 'where_to', 'pickup_location',
               'total_price', 'departure_date', 'humidity', 'wind', 'street_address', 'album', 'O'],

    'Services': ['ride_fare', 'therapist_name', 'event_location', 'movie_title', 'doctor_name', 'precipitation',
                 'genre', 'average_rating', 'cuisine',
                 'account_balance', 'approximate_ride_duration', 'date', 'phone_number', 'destination', 'address',
                 'percent_rating', 'cast', 'city',
                 'appointment_date', 'location', 'appointment_time', 'stylist_name', 'directed_by', 'wait_time',
                 'temperature',
                 'dentist_name', 'humidity', 'wind', 'street_address', 'movie_name', 'O'],

    'Homes': ['ride_fare', 'start_date', 'rent', 'area', 'approximate_ride_duration', 'phone_number', 'destination',
              'pickup_date', 'balance',
              'address', 'price', 'property_name', 'visit_date', 'alarm_name', 'pickup_time', 'wait_time',
              'pickup_location', 'total_price',
              'dropoff_date', 'alarm_time', 'O'],

    'Calendar': ['ride_fare', 'time', 'event_location', 'cuisine', 'approximate_ride_duration', 'date', 'phone_number',
                 'destination',
                 'address', 'property_name', 'event_date', 'city', 'available_start_time', 'visit_date',
                 'available_end_time', 'event_time', 'wait_time',
                 'dentist_name', 'venue_address', 'event_name', 'O'],

    'Weather': ['ride_fare', 'time', 'rating', 'attraction_name', 'movie_title', 'precipitation', 'genre', 'cuisine',
                'account_balance', 'track',
                'price_per_night', 'from', 'aggregate_rating', 'approximate_ride_duration', 'date', 'phone_number',
                'destination', 'check_in_date',
                'song_name', 'address', 'journey_start_time', 'to_station', 'hotel_name', 'percent_rating', 'director',
                'to', 'city', 'event_name',
                'visit_date', 'artist', 'wait_time', 'category', 'temperature', 'title', 'departure_date',
                'date_of_journey', 'humidity', 'venue',
                'from_station', 'wind', 'venue_address', 'street_address', 'album', 'O'],
    'Travel': ['album', 'ride_fare', 'starring', 'time', 'actors', 'rating', 'attraction_name', 'precipitation',
               'genre', 'average_rating',
               'account_balance', 'track', 'price_per_night', 'aggregate_rating', 'approximate_ride_duration',
               'phone_number', 'destination',
               'song_name', 'address', 'price', 'hotel_name', 'director', 'place_name', 'city', 'location', 'artist',
               'category', 'temperature',
               'title', 'departure_date', 'humidity', 'venue', 'wind', 'venue_address', 'street_address', 'movie_name',
               'event_name', 'O'],

    'others': ['ride_fare', 'starring', 'recipient_name', 'actors', 'time', 'rating', 'attraction_name', 'genre',
               'account_balance', 'from', 'date',
               'phone_number', 'destination', 'total', 'balance', 'recipient_account_name', 'transfer_amount',
               'address', 'journey_start_time', 'to_station',
               'price', 'new_alarm_time', 'director', 'contact_name', 'transfer_time', 'city', 'to', 'location',
               'alarm_name', 'directed_by',
               'price_per_ticket', 'new_alarm_name', 'wait_time', 'title', 'receiver', 'date_of_journey', 'amount',
               'venue', 'alarm_time',
               'from_station', 'venue_address', 'movie_name', 'event_name', 'O']}

multiwoz_labels = ['hotel-parking', 'restaurant-name', 'hotel-bookstay', 'taxi-destination', 'train-bookpeople',
                   'hotel-stars', 'restaurant-area', 'hotel-area',
                   'train-destination', 'hotel-internet', 'restaurant-bookday', 'restaurant-food',
                   'restaurant-booktime', 'hotel-bookpeople', 'hotel-bookday',
                   'train-departure', 'attraction-type', 'hotel-type', 'hospital-department', 'train-leaveat',
                   'bus-destination', 'restaurant-bookpeople',
                   'bus-departure', 'train-day', 'hotel-name', 'taxi-leaveat', 'taxi-arriveby', 'attraction-area',
                   'restaurant-pricerange', 'attraction-name',
                   'taxi-departure', 'train-arriveby', 'hotel-pricerange', 'O']

multiwoz_valid_labels = ['B-train-arriveby', 'B-attraction-name', 'I-restaurant-name', 'B-train-leaveat',
                         'B-taxi-departure', 'B-hotel-bookpeople', 'B-hotel-type',
                         'B-restaurant-pricerange', 'B-train-departure', 'B-train-bookpeople', 'I-train-arriveby',
                         'B-attraction-area', 'I-attraction-name',
                         'B-bus-departure', 'B-restaurant-bookday', 'B-restaurant-food', 'B-hotel-stars',
                         'B-taxi-arriveby', 'B-train-destination', 'I-train-leaveat',
                         'B-restaurant-name', 'B-hotel-bookstay', 'B-train-day', 'I-train-departure',
                         'B-hospital-department', 'B-restaurant-booktime',
                         'B-hotel-pricerange', 'I-hotel-name', 'I-hotel-type', 'B-bus-destination', 'I-taxi-leaveat',
                         'B-hotel-area', 'B-attraction-type',
                         'I-train-destination', 'I-hospital-department', 'B-restaurant-area', 'I-restaurant-food',
                         'I-attraction-type', 'I-hotel-stars',
                         'B-hotel-internet', 'I-restaurant-booktime', 'I-taxi-departure', 'B-taxi-leaveat',
                         'B-restaurant-bookpeople', 'I-taxi-arriveby',
                         'B-hotel-name', 'B-taxi-destination', 'B-hotel-bookday', 'I-taxi-destination',
                         'B-hotel-parking', 'O']

multiwoz_label_dict = {
    'find_restaurant': ['restaurant-food', 'restaurant-name', 'restaurant-booktime', 'hotel-name', 'taxi-destination',
                        'restaurant-pricerange',
                        'attraction-name', 'restaurant-area', 'taxi-departure', 'hospital-department',
                        'restaurant-bookpeople', 'restaurant-bookday', 'O'],

    'find_hotel': ['hotel-parking', 'restaurant-food', 'restaurant-name', 'hotel-name', 'taxi-destination',
                   'hotel-type', 'hotel-stars', 'taxi-arriveby',
                   'attraction-name', 'taxi-departure', 'hotel-area', 'hospital-department', 'hotel-internet',
                   'hotel-pricerange', 'O'],

    'book_hotel': ['hotel-parking', 'restaurant-booktime', 'restaurant-name', 'restaurant-food', 'hotel-name',
                   'hotel-bookstay', 'taxi-destination',
                   'hotel-stars', 'hotel-bookpeople', 'hotel-type', 'taxi-arriveby', 'taxi-leaveat', 'attraction-name',
                   'hotel-bookday', 'taxi-departure',
                   'hotel-area', 'hotel-pricerange', 'O'],

    'book_restaurant': ['restaurant-food', 'restaurant-booktime', 'restaurant-name', 'hotel-name', 'taxi-destination',
                        'taxi-leaveat',
                        'taxi-arriveby', 'restaurant-pricerange', 'restaurant-area', 'taxi-departure',
                        'hospital-department', 'train-arriveby',
                        'restaurant-bookpeople', 'restaurant-bookday', 'O'],

    'find_taxi': ['restaurant-booktime', 'hotel-name', 'taxi-destination', 'taxi-leaveat', 'taxi-arriveby',
                  'attraction-name', 'taxi-departure',
                  'hospital-department', 'O'],

    'find_train': ['train-day', 'restaurant-food', 'restaurant-name', 'restaurant-booktime', 'hotel-name',
                   'taxi-destination',
                   'train-bookpeople', 'taxi-leaveat', 'attraction-name', 'train-departure', 'taxi-departure',
                   'train-destination',
                   'train-leaveat', 'train-arriveby', 'O'],

    'book_train': ['train-day', 'restaurant-food', 'restaurant-name', 'hotel-name', 'train-bookpeople',
                   'attraction-name', 'train-departure',
                   'train-destination', 'train-leaveat', 'train-arriveby', 'O'],

    'find_attraction': ['restaurant-food', 'restaurant-name', 'hotel-name', 'taxi-destination', 'attraction-area',
                        'taxi-arriveby',
                        'taxi-leaveat', 'attraction-name', 'taxi-departure', 'hospital-department', 'attraction-type',
                        'O'],
    'others': ['taxi-destination', 'bus-departure', 'hospital-department', 'bus-destination', 'O']}

atis_index_dict = {}
for key, values in atis_label_dict.items():
    tmp = [atis_labels.index(v) for v in values]
    atis_index_dict[key] = tmp

sgd_index_dict = {}
for key, values in sgd_label_dict.items():
    tmp = [sgd_labels.index(v) for v in values]
    sgd_index_dict[key] = tmp

multiwoz_index_dict = {}
for key, values in multiwoz_label_dict.items():
    tmp = [multiwoz_labels.index(v) for v in values]
    multiwoz_index_dict[key] = tmp
